const SavedActionTypes = {
  TOGGLE_SAVED_HIDDEN: 'TOGGLE_SAVED_HIDDEN',
  SET_SAVED: 'SET_SAVED',
  ADD_SAVED_START: 'ADD_SAVED_START',
  ADD_SAVED_SUCCESS: 'ADD_SAVED_SUCCESS',
  ADD_SAVED_FAILURE: 'ADD_SAVED_FAILURE',
  FETCH_SAVED_START: 'FETCH_SAVED_START',
  FETCH_SAVED_SUCCESS: 'FETCH_SAVED_SUCCESS',
  FETCH_SAVED_FAILURE: 'FETCH_SAVED_FAILURE',
  DELETE_SAVED_START: 'DELETE_SAVED_START',
  DELETE_SAVED_SUCCESS: 'DELETE_SAVED_SUCCESS',
  DELETE_SAVED_FAILURE: 'DELETE_SAVED_FAILURE',
};

export default SavedActionTypes;
