const SavedActionTypes = {
  ADD_SAVED_START: 'ADD_SAVED_START',
  ADD_SAVED_SUCCESS: 'ADD_SAVED_SUCCESS',
  ADD_SAVED_FAILURE: 'ADD_SAVED_FAILURE',
  FETCH_SAVED_START: 'FETCH_SAVED_START',
  FETCH_SAVED_SUCCESS: 'FETCH_SAVED_SUCCESS',
  FETCH_SAVED_FAILURE: 'FETCH_SAVED_FAILURE',
};

export default SavedActionTypes;
