export const SearchActionTypes = {
	FETCH_SEARCH_START: 'FETCH_SEARCH_START',
	FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
	FETCH_SEARCH_FAILURE: 'FETCH_SEARCH_FAILURE',

	FETCH_RECOMMENDED_START: 'FETCH_RECOMMENDED_START',
	FETCH_RECOMMENDED_SUCCESS: 'FETCH_RECOMMENDED_SUCCESS',
	FETCH_RECOMMENDED_FAILURE: 'FETCH_RECOMMENDED_FAILURE',

	FETCH_POPULAR_START: 'FETCH_POPULAR_START',
	FETCH_POPULAR_SUCCESS: 'FETCH_POPULAR_SUCCESS',
	FETCH_POPULAR_FAILURE: 'FETCH_POPULAR_FAILURE',


	FETCH_SIMILAR_START: 'FETCH_SIMILAR_START',
	FETCH_SIMILAR_SUCCESS: 'FETCH_SIMILAR_SUCCESS',
	FETCH_SIMILAR_FAILURE: 'FETCH_SIMILAR_FAILURE',

	UPDATE_USER_SEARCH_INPUT: 'UPDATE_USER_SEARCH_INPUT',

	UPDATE_FIND_SIMILAR_QUERY: 'UPDATE_FIND_SIMILAR_QUERY',

	SORT_RESULTS_DISPLAY: 'SORT_RESULTS_DISPLAY',
};
